export { Home } from "./Home/Home";
export { Quizes } from "./Quizes/Quizes";
export { QuizComp } from "./Quiz/Quiz";
export { Result } from "./Result/Result";
export { Rules } from "./Rules/Rules";
export { Login } from "./Login/Login";
export { Signup } from "./Signup/Signup";
export { Account } from "./Account/Account";
export { QuizBoard } from "./QuizBoard/QuizBoard";
